### ISSUE TITLE
一樣是慕瑪的錯誤

### ISSUE THREAD

**Issue by matiffeder** [progheal/nekowiz-poten#2]
![2](https://cloud.githubusercontent.com/assets/2030916/10538342/7846593a-742a-11e5-9a13-f1dbab22f65e.png)
在計算已有兩潛的S紅慕瑪並沒有用最少的卡片數計算
如圖，最少的卡片的計算方式應為右圖（條件「已有無潛的S紅慕瑪」）的總卡片減六，共14張
但實際上若我的條件改為「已有兩潛的S紅慕瑪」在計算時則需求卡數會多出兩張，如圖左

如您找的到方法修正的話就麻煩您了~
非常感謝您做出這麼好用的東西
另外，阿修羅王和維若妮卡的圖放錯了喔~~

**Comment by progheal** [comment]
慕瑪的問題：
你的比較基準不太對：你的右圖是「有無潛 S 紅慕瑪」，但左圖卻只是「有二潛 S 紅慕瑪」，因此右邊因為有無潛紅慕瑪所省下的卡在左邊並沒有省到。
如果條件是「有 S 紅慕瑪無潛二潛各一張」則求出來確實是 14 張無誤：
![2015-10-16 19 34 57](https://cloud.githubusercontent.com/assets/4156121/10540768/9c7b9bfe-743d-11e5-9045-869506800f41.png)

圖示問題：可否截個圖讓我看一下是哪個地方放錯了？我這裡目前看起來都是對的。(除了阿修羅王的 SS 級圖示是無邊框圖之外)

**Comment by matiffeder** [comment]
真的耶，我少算了最右邊的S慕馬還要三張，哈哈~
另外這是我這邊顯示的圖示
![1](https://cloud.githubusercontent.com/assets/2030916/10549157/ee39a8b2-7471-11e5-9c58-97ce6b82f790.png)

**Comment by progheal** [comment]
唔嗯...這有點詭異，因為你這張圖裡不只你提到的這兩張錯，灰階那張卡圖上是圓仔，但應該要是 SS 級佩特拉的。
可以提供一下你的瀏覽器跟作業系統環境嗎？
同時你可以試著清一下瀏覽器快取再重新載入一次看看，說不定就沒問題了。

**Comment by matiffeder** [comment]
我清除了 quiz-wiz.com 的 com_id 這個 cookie 就好了~
謝謝你喔

**Comment by progheal** [comment]
OK, issue closed.
