### ISSUE TITLE
魔導杯的卡片

### ISSUE THREAD

**Issue by balvin0059** [progheal/nekowiz-poten#3]
您好，想請問下能不能添加這次萬聖節魔導杯的卡片呢，拜託了><

**Comment by progheal** [comment]
一般來說魔導盃的卡片是不會放進來的，主要是因為通常只能獲得剛好升滿的卡片量；
不過因為這次的魔導盃獎勵每日排名的卡片大家都能獲得足量滿潛卡，加上因為重開，個人排名的獎勵卡也能多拿，所以就一併新增了 :D
