### ISSUE TITLE
幻魔特區滿潛所需卡片張數未計算到進化用素材

### ISSUE THREAD

**Issue by hannahchao** [progheal/nekowiz-poten#5]
如題,
![cc](https://cloud.githubusercontent.com/assets/12669463/13595711/a4de531e-e548-11e5-90e0-e285de032ce8.png)

從圖中應該可以看出假定我們選擇滿潛的威爾戈,
剩餘的所需張數似乎僅計算了樹的末端的張數,
而並不包含各層中進化所需的B+威爾戈

**Comment by progheal** [comment]
這問題在[推特上](https://twitter.com/calvin1002/status/707038559320956928)也有人回報了，目前已修復，請再試試看 :)
