### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ccj242** [progheal/nekowiz-poten#6]
Hi - very sorry for posting here, but I wasn't sure how else make contact and I was hoping to send you a message. Your very thoughtful and comprehensive feedback on Copy Editor a awhile ago stuck with me and I was hoping to discuss some collaboration possibilities. If you're interested in chatting, shoot me an email at info@cinqmarsmedia.org and please feel free to close this issue. Thanks!

**Comment by progheal** [comment]
Thanks for the heads up, but currently I don't have the plan on such collaborations.
